apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: obb882da7-dotnet-basic 
  janus-idp.io/tekton: obb882da7-dotnet-basic
  backstage.io/kubernetes-id: obb882da7-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: obb882da7-dotnet-basic
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml